
package ServerFromWSDL_Tomcat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloServletService", targetNamespace = "http://server_tomcat.example.org/", wsdlLocation = "http://localhost:8080/RSI_ZAD6_Tomcat/hello-servlet?wsdl")
public class HelloServletService
    extends Service
{

    private final static URL HELLOSERVLETSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVLETSERVICE_EXCEPTION;
    private final static QName HELLOSERVLETSERVICE_QNAME = new QName("http://server_tomcat.example.org/", "HelloServletService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/RSI_ZAD6_Tomcat/hello-servlet?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVLETSERVICE_WSDL_LOCATION = url;
        HELLOSERVLETSERVICE_EXCEPTION = e;
    }

    public HelloServletService() {
        super(__getWsdlLocation(), HELLOSERVLETSERVICE_QNAME);
    }

    public HelloServletService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVLETSERVICE_QNAME, features);
    }

    public HelloServletService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVLETSERVICE_QNAME);
    }

    public HelloServletService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVLETSERVICE_QNAME, features);
    }

    public HelloServletService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServletService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloServlet
     */
    @WebEndpoint(name = "HelloServletPort")
    public HelloServlet getHelloServletPort() {
        return super.getPort(new QName("http://server_tomcat.example.org/", "HelloServletPort"), HelloServlet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServlet
     */
    @WebEndpoint(name = "HelloServletPort")
    public HelloServlet getHelloServletPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server_tomcat.example.org/", "HelloServletPort"), HelloServlet.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVLETSERVICE_EXCEPTION!= null) {
            throw HELLOSERVLETSERVICE_EXCEPTION;
        }
        return HELLOSERVLETSERVICE_WSDL_LOCATION;
    }

}
