
package ServerFromWSDL_Tomcat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServlet", targetNamespace = "http://server_tomcat.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServlet {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://server_tomcat.example.org/", className = "ServerFromWSDL_Tomcat.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://server_tomcat.example.org/", className = "ServerFromWSDL_Tomcat.EchoResponse")
    @Action(input = "http://server_tomcat.example.org/HelloServlet/echoRequest", output = "http://server_tomcat.example.org/HelloServlet/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://server_tomcat.example.org/", className = "ServerFromWSDL_Tomcat.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://server_tomcat.example.org/", className = "ServerFromWSDL_Tomcat.DownloadImageResponse")
    @Action(input = "http://server_tomcat.example.org/HelloServlet/downloadImageRequest", output = "http://server_tomcat.example.org/HelloServlet/downloadImageResponse")
    public byte[] downloadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
