
package ex1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShopInfo", targetNamespace = "http://ex1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShopInfo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShopInfo", targetNamespace = "http://ex1/", className = "ex1.GetShopInfo")
    @ResponseWrapper(localName = "getShopInfoResponse", targetNamespace = "http://ex1/", className = "ex1.GetShopInfoResponse")
    @Action(input = "http://ex1/ShopInfo/getShopInfoRequest", output = "http://ex1/ShopInfo/getShopInfoResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://ex1/ShopInfo/getShopInfo/Fault/InvalidInputException")
    })
    public String getShopInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InvalidInputException_Exception
    ;

}
