
package soap.Client1.GeneratedByWsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerHelloWorldService", targetNamespace = "http://Server.soap/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class ServerHelloWorldService
    extends Service
{

    private final static URL SERVERHELLOWORLDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERHELLOWORLDSERVICE_EXCEPTION;
    private final static QName SERVERHELLOWORLDSERVICE_QNAME = new QName("http://Server.soap/", "ServerHelloWorldService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERHELLOWORLDSERVICE_WSDL_LOCATION = url;
        SERVERHELLOWORLDSERVICE_EXCEPTION = e;
    }

    public ServerHelloWorldService() {
        super(__getWsdlLocation(), SERVERHELLOWORLDSERVICE_QNAME);
    }

    public ServerHelloWorldService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERHELLOWORLDSERVICE_QNAME, features);
    }

    public ServerHelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVERHELLOWORLDSERVICE_QNAME);
    }

    public ServerHelloWorldService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERHELLOWORLDSERVICE_QNAME, features);
    }

    public ServerHelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerHelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServerHelloWorld
     */
    @WebEndpoint(name = "ServerHelloWorldPort")
    public IServerHelloWorld getServerHelloWorldPort() {
        return super.getPort(new QName("http://Server.soap/", "ServerHelloWorldPort"), IServerHelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerHelloWorld
     */
    @WebEndpoint(name = "ServerHelloWorldPort")
    public IServerHelloWorld getServerHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server.soap/", "ServerHelloWorldPort"), IServerHelloWorld.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERHELLOWORLDSERVICE_EXCEPTION!= null) {
            throw SERVERHELLOWORLDSERVICE_EXCEPTION;
        }
        return SERVERHELLOWORLDSERVICE_WSDL_LOCATION;
    }

}
